"""
Django settings for webapps2025 project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# ✅ Base Directory
BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ Security Settings
SECRET_KEY = "django-insecure-u7bx1!ya5#p%in^*j(6jn09&%6ce!ljq-v9y$73ushmh8ae4^$"
DEBUG = True  # ⚠️ Keep False in Production

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']  # Allow localhost connections

# ✅ Installed Applications
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'register',  # User authentication
    'payapp',    # Payment functionalities
    'sslserver',  # HTTPS Support in Development (Remove in Production)
    'crispy_forms',
    'crispy_bootstrap5',
    'currency_api',  # ✅ Add this for Bootstrap 5 support
]

CRISPY_TEMPLATE_PACK = "bootstrap5"

# ✅ Authentication Settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ✅ Security & CSRF Protection
SECURE_SSL_REDIRECT = False  # Enable in production
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False


# Clickjacking Protection
X_FRAME_OPTIONS = 'DENY'

# HTTP Security Headers
SECURE_HSTS_SECONDS = 31536000  # 1-year enforcement
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# ✅ Middleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ✅ URL Configuration
ROOT_URLCONF = "webapps2025.urls"

# ✅ Templates Configuration
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",  # Global templates directory
        ],
        "APP_DIRS": True,  # Enables template loading from app directories
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ✅ WSGI Application
WSGI_APPLICATION = "webapps2025.wsgi.application"

# ✅ Database Configuration (PostgreSQL)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'webapp',
#         'USER': 'aa2860',
#         'PASSWORD': 'aa2860',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

# ✅ Database Configuration (SQLite for development)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'webapps.db',  # SQLite database file
    }
}
# ✅ Password Validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ✅ Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ✅ Static Files
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]  # Static files for development
STATIC_ROOT = BASE_DIR / "staticfiles"  # Collected static files for production
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"  # Default storage

# ✅ Media Files (For user-uploaded content)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ✅ Default Primary Key Type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
